import Head from 'next/head';
import {Montserrat} from 'next/font/google';
import Button from '@/components/Button/Button';
import Arrow from '../public/arrow.svg';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '400', '700'],
  display: 'swap',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${montserrat.style.fontFamily};
        }
      `}</style>
      <main>
        <h1>Heading 1</h1>
        <div>Text</div>
        <Button type='primary'>купить</Button>
        <Button type='ghost' icon={<Arrow />} iconPosition='right'>
          заказать КП
        </Button>
      </main>
    </>
  );
}
