import Head from 'next/head';
import {Montserrat} from 'next/font/google';
import Button from '@/components/Button/Button';
import Arrow from '../public/arrow.svg';
import Heading from '@/components/Heading/Heading';
import Paragraph from '@/components/Paragraph/Paragraph';
import Layout from '@/layout/Layout';
import Container from '@/layout/Container/Container';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '400', '700'],
  display: 'swap',
  fallback: ['Arial', 'san-serif'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>5drops Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${montserrat.style.fontFamily};
        }
      `}</style>
      <Layout>
        <Container>
          <Heading tag='h1'>Heading 1</Heading>
          <Heading tag='h2'>Heading 2</Heading>
          <Heading tag='h3'>Heading 3</Heading>
          <Heading tag='h4'>Heading 4</Heading>
          <Paragraph>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde nesciunt, sequi cum nemo
            deserunt eos saepe tempore numquam tenetur facere harum porro optio necessitatibus
            quaerat consequatur vitae sint aperiam! Sequi.
          </Paragraph>

          <Button type='primary'>купить</Button>
          <Button type='ghost' icon={<Arrow />} iconPosition='right'>
            заказать КП
          </Button>
        </Container>
      </Layout>
    </>
  );
}
